const ARTIST_GENRES_MAP = {
    "aespa": ["k-pop", "pop", "electropop"],
    "ariana grande": ["pop", "r&b", "dance-pop"],
    "billie eilish": ["pop", "alt-pop", "electropop"],
    "kikuo": ["vocaloid", "j-pop", "electronic"],
    "melanie martinez": ["alt-pop", "pop", "indie pop"],
    "sabrina carpenter": ["pop", "dance-pop"],
    "olivia rodrigo": ["pop", "alt-pop", "pop-punk"],
    "pinkpantheress": ["drum and bass", "bedroom pop", "uk garage"],
    "lana del rey": ["art pop", "indie pop", "pop"],
    "britney spears": ["pop", "dance-pop"],
    "gracie abrams": ["indie pop", "singer-songwriter", "pop"],
    "blackpink": ["k-pop", "pop"],
    "cigarettes after sex": ["dream pop", "slowcore", "indie pop"],
    "taylor swift": ["pop", "synth-pop", "folk-pop"],
    "madison beer": ["pop", "r&b"],
    "newjeans": ["k-pop", "pop", "r&b"],
    "le sserafim": ["k-pop", "j-pop", "electropop"],
    "yandere": ["electronic", "breakcore"],
    "paramore": ["alt-rock", "pop-punk", "indie rock"],
    "justin bieber": ["pop", "dance-pop", "r&b"],
    "ninajirachi": ["electronic", "hyperpop", "future bass"],
    "lisa": ["k-pop", "pop", "hip-hop"],
    "drake": ["hip-hop", "rap", "r&b"],
    "charli xcx": ["hyperpop", "pop", "electropop"],
    "joji": ["r&b", "lo-fi", "alt-pop"],
    "babymonster": ["k-pop", "hip-hop", "pop"],
    "nmixx": ["k-pop", "pop", "mixx-pop"],
    "joe hisaishi": ["anime", "soundtrack", "classical"],
    "jennie": ["k-pop", "hip-hop", "pop"],
    "doja cat": ["pop", "rap", "r&b"],
    "ive": ["k-pop", "pop"],
    "illit": ["k-pop", "pop"],
    "i just want to hold her": ["indie", "dream pop"],
    "akugetsu": ["electronic", "phonk", "breakcore"],
    "michael jackson": ["pop", "soul", "funk"],
    "i.m_kami": ["lofi", "hip-hop"],
    "malcolm todd": ["indie", "r&b", "pop"],
    "adéla": ["pop", "indie"],
    "the weeknd": ["pop", "r&b", "synth-pop"],
    "labrinth": ["r&b", "pop", "electronic"],
    "ice spice": ["rap", "drill", "hip-hop"],
    "gfriend": ["k-pop", "pop"],
    "akiradoves": ["electronic", "breakcore", "atmospheric dnb"],
    "owtiss": ["lofi", "electronic"],
    "the neighbourhood": ["alt-indie", "indie pop", "alt-rock"],
    "laufey": ["jazz", "pop", "bedroom pop"],
    "playboi carti": ["rap", "trap", "hip-hop"],
    "cursedcry": ["electronic", "breakcore"],
    "sza": ["r&b", "pop", "soul"],
    "ethel cain": ["indie pop", "alt-pop", "slowcore"],
    "daft punk": ["electronic", "house", "synth-pop"],
    "kanye west": ["hip-hop", "rap", "art pop"],
    "travis scott": ["hip-hop", "rap", "trap"],
    "kendrick lamar": ["hip-hop", "rap", "conscious hip hop"],
    "tyler, the creator": ["hip-hop", "rap", "neo-soul"],
    "frank ocean": ["r&b", "neo-soul", "pop"],
    "dua lipa": ["pop", "dance-pop", "disco"],
    "ed sheeran": ["pop", "singer-songwriter"],
    "coldplay": ["pop rock", "alt-rock", "pop"],
    "radiohead": ["art rock", "alt-rock", "electronic"],
    "the beatles": ["rock", "pop", "psychedelic rock"],
    "queen": ["rock", "hard rock", "glam rock"],
    "eminem": ["hip-hop", "rap"],
    "mac miller": ["hip-hop", "rap", "r&b"],
    "kid cudi": ["hip-hop", "rap", "alt-pop"],
    "post malone": ["pop", "hip-hop", "r&b"],
    "rihanna": ["pop", "r&b", "dance-pop"],
    "beyonce": ["pop", "r&b", "soul"],
    "adele": ["pop", "soul"],
    "harry styles": ["pop", "pop rock", "indie pop"],
    "tame impala": ["psychedelic pop", "synth-pop", "indie rock"],
    "clairo": ["indie pop", "bedroom pop", "soft rock"],
    "boygenius": ["indie rock", "indie pop"],
    "phoebe bridgers": ["indie pop", "singer-songwriter"],
    "mitski": ["art pop", "indie rock", "alt-rock"],
    "steve lacy": ["r&b", "indie soul", "funk"],
    "kali uchis": ["r&b", "pop", "indie soul"],
    "chappell roan": ["pop", "synth-pop", "indie pop"],
    "lorde": ["art pop", "pop", "electropop"],
    "gorillaz": ["art pop", "alternative", "electronic"],
    "central cee": ["rap", "drill", "uk hip hop"],
    "gazo": ["rap", "drill", "french hip hop"],
    "jul": ["rap", "french hip hop", "pop rap"],
    "ninho": ["rap", "french hip hop", "pop rap"],
    "damso": ["rap", "french hip hop", "art rap"],
    "orelsan": ["rap", "french hip hop"],
    "stromae": ["pop", "electronic", "chanson"],
    "nekfeu": ["rap", "french hip hop"],
    "laylow": ["rap", "french hip hop", "art rap"],
    "plk": ["rap", "french hip hop"],
    "hamza": ["rap", "r&b", "trap"],
    "sch": ["rap", "french hip hop", "trap"],
    "sdm": ["rap", "french hip hop"],
    "tiakola": ["rap", "afropop", "french hip hop"],
    "werenoi": ["rap", "french hip hop"],
    "pnl": ["rap", "cloud rap", "french hip hop"],
    "freeze corleone": ["rap", "drill", "french hip hop"]
};

module.exports = ARTIST_GENRES_MAP;
