const ARTIST_GENRES_MAP = {
    "aespa": ["k-pop", "pop", "electropop"],
    "ariana grande": ["pop", "r&b", "dance-pop"],
    "billie eilish": ["pop", "alt-pop", "electropop"],
    "kikuo": ["vocaloid", "j-pop", "electronic"],
    "melanie martinez": ["alt-pop", "pop", "indie pop"],
    "sabrina carpenter": ["pop", "dance-pop"],
    "olivia rodrigo": ["pop", "alt-pop", "pop-punk"],
    "pinkpantheress": ["drum and bass", "bedroom pop", "uk garage"],
    "lana del rey": ["art pop", "indie pop", "pop"],
    "britney spears": ["pop", "dance-pop"],
    "gracie abrams": ["indie pop", "singer-songwriter", "pop"],
    "blackpink": ["k-pop", "pop"],
    "cigarettes after sex": ["dream pop", "slowcore", "indie pop"],
    "taylor swift": ["pop", "synth-pop", "folk-pop"],
    "madison beer": ["pop", "r&b"],
    "newjeans": ["k-pop", "pop", "r&b"],
    "le sserafim": ["k-pop", "j-pop", "electropop"],
    "yandere": ["electronic", "breakcore"],
    "paramore": ["alt-rock", "pop-punk", "indie rock"],
    "justin bieber": ["pop", "dance-pop", "r&b"],
    "ninajirachi": ["electronic", "hyperpop", "future bass"],
    "lisa": ["k-pop", "pop", "hip-hop"],
    "drake": ["hip-hop", "rap", "r&b"],
    "charli xcx": ["hyperpop", "pop", "electropop"],
    "joji": ["r&b", "lo-fi", "alt-pop"],
    "babymonster": ["k-pop", "hip-hop", "pop"],
    "nmixx": ["k-pop", "pop", "mixx-pop"],
    "joe hisaishi": ["anime", "soundtrack", "classical"],
    "jennie": ["k-pop", "hip-hop", "pop"],
    "doja cat": ["pop", "rap", "r&b"],
    "ive": ["k-pop", "pop"],
    "illit": ["k-pop", "pop"],
    "i just want to hold her": ["indie", "dream pop"],
    "akugetsu": ["electronic", "phonk", "breakcore"],
    "michael jackson": ["pop", "soul", "funk"],
    "i.m_kami": ["lofi", "hip-hop"],
    "malcolm todd": ["indie", "r&b", "pop"],
    "adéla": ["pop", "indie"],
    "the weeknd": ["pop", "r&b", "synth-pop"],
    "labrinth": ["r&b", "pop", "electronic"],
    "ice spice": ["rap", "drill", "hip-hop"],
    "gfriend": ["k-pop", "pop"],
    "akiradoves": ["electronic", "breakcore", "atmospheric dnb"],
    "owtiss": ["lofi", "electronic"],
    "the neighbourhood": ["alt-indie", "indie pop", "alt-rock"],
    "laufey": ["jazz", "pop", "bedroom pop"],
    "playboi carti": ["rap", "trap", "hip-hop"],
    "cursedcry": ["electronic", "breakcore"],
    "sza": ["r&b", "pop", "soul"],
    "ethel cain": ["indie pop", "alt-pop", "slowcore"],
    "daft punk": ["electronic", "house", "synth-pop"],
    "kanye west": ["hip-hop", "rap", "art pop"],
    "travis scott": ["hip-hop", "rap", "trap"],
    "kendrick lamar": ["hip-hop", "rap", "conscious hip hop"],
    "tyler, the creator": ["hip-hop", "rap", "neo-soul"],
    "frank ocean": ["r&b", "neo-soul", "pop"],
    "dua lipa": ["pop", "dance-pop", "disco"],
    "ed sheeran": ["pop", "singer-songwriter"],
    "coldplay": ["pop rock", "alt-rock", "pop"],
    "radiohead": ["art rock", "alt-rock", "electronic"],
    "the beatles": ["rock", "pop", "psychedelic rock"],
    "queen": ["rock", "hard rock", "glam rock"],
    "eminem": ["hip-hop", "rap"],
    "mac miller": ["hip-hop", "rap", "r&b"],
    "kid cudi": ["hip-hop", "rap", "alt-pop"],
    "post malone": ["pop", "hip-hop", "r&b"],
    "rihanna": ["pop", "r&b", "dance-pop"],
    "beyonce": ["pop", "r&b", "soul"],
    "adele": ["pop", "soul"],
    "harry styles": ["pop", "pop rock", "indie pop"],
    "tame impala": ["psychedelic pop", "synth-pop", "indie rock"],
    "clairo": ["indie pop", "bedroom pop", "soft rock"],
    "boygenius": ["indie rock", "indie pop"],
    "phoebe bridgers": ["indie pop", "singer-songwriter"],
    "mitski": ["art pop", "indie rock", "alt-rock"],
    "steve lacy": ["r&b", "indie soul", "funk"],
    "kali uchis": ["r&b", "pop", "indie soul"],
    "chappell roan": ["pop", "synth-pop", "indie pop"],
    "lorde": ["art pop", "pop", "electropop"],
    "gorillaz": ["art pop", "alternative", "electronic"],
    "central cee": ["rap", "drill", "uk hip hop"],
    "gazo": ["rap", "drill", "french hip hop"],
    "jul": ["rap", "french hip hop", "pop rap"],
    "ninho": ["rap", "french hip hop", "pop rap"],
    "damso": ["rap", "french hip hop", "art rap"],
    "orelsan": ["rap", "french hip hop"],
    "stromae": ["pop", "electronic", "chanson"],
    "nekfeu": ["rap", "french hip hop"],
    "laylow": ["rap", "french hip hop", "art rap"],
    "plk": ["rap", "french hip hop"],
    "hamza": ["rap", "r&b", "trap"],
    "sch": ["rap", "french hip hop", "trap"],
    "sdm": ["rap", "french hip hop"],
    "tiakola": ["rap", "afropop", "french hip hop"],
    "werenoi": ["rap", "french hip hop"],
    "pnl": ["rap", "cloud rap", "french hip hop"],
    "freeze corleone": ["rap", "drill", "french hip hop"]
};

const POPULAR_ARTISTS_STATS = {
    "aespa": { popularity: 82, followers: 5200000, monthlyListeners: 12500000 },
    "ariana grande": { popularity: 92, followers: 96000000, monthlyListeners: 82000000 },
    "billie eilish": { popularity: 93, followers: 94000000, monthlyListeners: 99500000 },
    "kikuo": { popularity: 68, followers: 850000, monthlyListeners: 1800000 },
    "melanie martinez": { popularity: 82, followers: 16000000, monthlyListeners: 15000000 },
    "sabrina carpenter": { popularity: 91, followers: 18000000, monthlyListeners: 85000000 },
    "olivia rodrigo": { popularity: 88, followers: 38000000, monthlyListeners: 58000000 },
    "pinkpantheress": { popularity: 76, followers: 2500000, monthlyListeners: 14000000 },
    "lana del rey": { popularity: 89, followers: 39000000, monthlyListeners: 54000000 },
    "britney spears": { popularity: 81, followers: 15000000, monthlyListeners: 28000000 },
    "gracie abrams": { popularity: 84, followers: 4000000, monthlyListeners: 32000000 },
    "blackpink": { popularity: 83, followers: 49000000, monthlyListeners: 18000000 },
    "cigarettes after sex": { popularity: 82, followers: 8000000, monthlyListeners: 24000000 },
    "taylor swift": { popularity: 98, followers: 120000000, monthlyListeners: 95000000 },
    "madison beer": { popularity: 78, followers: 7500000, monthlyListeners: 16000000 },
    "newjeans": { popularity: 81, followers: 8500000, monthlyListeners: 16500000 },
    "le sserafim": { popularity: 80, followers: 4200000, monthlyListeners: 11500000 },
    "paramore": { popularity: 78, followers: 8500000, monthlyListeners: 19000000 },
    "justin bieber": { popularity: 89, followers: 76000000, monthlyListeners: 72000000 },
    "lisa": { popularity: 79, followers: 9000000, monthlyListeners: 17000000 },
    "drake": { popularity: 94, followers: 89000000, monthlyListeners: 78000000 },
    "charli xcx": { popularity: 86, followers: 5800000, monthlyListeners: 42000000 },
    "joji": { popularity: 81, followers: 9500000, monthlyListeners: 23000000 },
    "doja cat": { popularity: 87, followers: 30000000, monthlyListeners: 52000000 },
    "michael jackson": { popularity: 88, followers: 33000000, monthlyListeners: 41000000 },
    "the weeknd": { popularity: 96, followers: 87000000, monthlyListeners: 120000000 },
    "playboi carti": { popularity: 89, followers: 11000000, monthlyListeners: 45000000 },
    "sza": { popularity: 89, followers: 23000000, monthlyListeners: 58000000 },
    "daft punk": { popularity: 83, followers: 18000000, monthlyListeners: 48000000 },
    "kanye west": { popularity: 92, followers: 25000000, monthlyListeners: 62000000 },
    "travis scott": { popularity: 91, followers: 31000000, monthlyListeners: 64000000 },
    "kendrick lamar": { popularity: 91, followers: 29000000, monthlyListeners: 66000000 },
    "tyler, the creator": { popularity: 87, followers: 15000000, monthlyListeners: 33000000 },
    "frank ocean": { popularity: 83, followers: 14000000, monthlyListeners: 28000000 },
    "dua lipa": { popularity: 90, followers: 44000000, monthlyListeners: 74000000 },
    "ed sheeran": { popularity: 91, followers: 115000000, monthlyListeners: 72000000 },
    "coldplay": { popularity: 91, followers: 52000000, monthlyListeners: 78000000 },
    "radiohead": { popularity: 80, followers: 9800000, monthlyListeners: 22000000 },
    "the beatles": { popularity: 86, followers: 29000000, monthlyListeners: 35000000 },
    "queen": { popularity: 85, followers: 50000000, monthlyListeners: 48000000 },
    "eminem": { popularity: 92, followers: 88000000, monthlyListeners: 68000000 },
    "rihanna": { popularity: 89, followers: 60000000, monthlyListeners: 76000000 },
    "beyonce": { popularity: 89, followers: 37000000, monthlyListeners: 48000000 },
    "adele": { popularity: 87, followers: 54000000, monthlyListeners: 52000000 },
    "harry styles": { popularity: 85, followers: 32000000, monthlyListeners: 46000000 },
    "tame impala": { popularity: 80, followers: 9200000, monthlyListeners: 24000000 },
    "clairo": { popularity: 77, followers: 5500000, monthlyListeners: 13000000 },
    "mitski": { popularity: 81, followers: 7500000, monthlyListeners: 25000000 },
    "chappell roan": { popularity: 88, followers: 3000000, monthlyListeners: 45000000 },
    "lorde": { popularity: 76, followers: 11000000, monthlyListeners: 15000000 },
    "gorillaz": { popularity: 79, followers: 12000000, monthlyListeners: 23000000 },
    "stromae": { popularity: 74, followers: 5800000, monthlyListeners: 10500000 }
};

module.exports = {
    ARTIST_GENRES_MAP,
    POPULAR_ARTISTS_STATS
};
